source: content
paths:
  data: ../_data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  posts:
    path: blog
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: ../_data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
data_config: {}
timezone: US/Pacific
